import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { fetchRecommendationHistoryApi } from '../services/api';
import { History, Sprout, Calendar, CheckCircle2, ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const RecommendationHistory = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadHistory = async () => {
      try {
        const data = await fetchRecommendationHistoryApi();
        setHistory(data);
      } catch (err) {
        console.error("Failed to fetch recommendation history", err);
      } finally {
        setLoading(false);
      }
    };
    loadHistory();
  }, []);

  return (
    <div className="py-12 max-w-6xl mx-auto px-4 sm:px-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300 font-bold text-xs mb-3">
            <History className="w-3.5 h-3.5 text-primary" />
            AI Recommendation Log
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            Recommendation History
          </h1>
          <p className="text-slate-500 dark:text-slate-400 mt-1 text-sm sm:text-base">
            Review past crop recommendations generated by our AI engine.
          </p>
        </div>
        
        <Link 
          to="/crop-recommendation" 
          className="flex items-center gap-2 px-6 py-3 bg-primary hover:bg-primary-dark text-white font-bold rounded-xl shadow-lg shadow-primary/30 transition-all text-sm"
        >
          <Sprout className="w-4 h-4" /> New Prediction
        </Link>
      </div>

      {loading ? (
        <div className="flex justify-center py-20">
          <div className="w-10 h-10 border-4 border-emerald-500/30 border-t-emerald-500 rounded-full animate-spin"></div>
        </div>
      ) : history.length === 0 ? (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="saas-card p-12 text-center max-w-xl mx-auto flex flex-col items-center"
        >
          <div className="w-20 h-20 rounded-full bg-emerald-50 dark:bg-slate-800 flex items-center justify-center text-primary mb-4">
            <History className="w-10 h-10" />
          </div>
          <h3 className="text-2xl font-extrabold text-slate-800 dark:text-white mb-2">No History Found</h3>
          <p className="text-slate-500 dark:text-slate-400 mb-6 text-sm">
            You haven't run any AI crop recommendations yet. Go to the prediction engine to generate your first report.
          </p>
        </motion.div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {history.map((item, index) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="saas-card p-6 flex flex-col justify-between hover:border-emerald-300 dark:hover:border-emerald-700 transition-all"
            >
              <div className="flex justify-between items-start mb-4">
                <div>
                  <h3 className="text-xl font-extrabold text-slate-900 dark:text-white mb-1">{item.recommended_crop}</h3>
                  <p className="text-xs text-slate-500 font-medium flex items-center gap-1">
                    <Calendar className="w-3.5 h-3.5" /> 
                    {new Date(item.created_at).toLocaleDateString()}
                  </p>
                </div>
                <div className="bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 px-2 py-1 rounded text-xs font-bold flex items-center gap-1">
                  <CheckCircle2 className="w-3 h-3" /> {item.confidence}%
                </div>
              </div>

              <div className="bg-slate-50 dark:bg-slate-900/60 p-4 rounded-xl border border-slate-100 dark:border-slate-800 mb-4 text-sm space-y-2">
                <div className="flex justify-between">
                  <span className="text-slate-500">Farm:</span>
                  <span className="font-semibold text-slate-700 dark:text-slate-200">{item.farm_name}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Season:</span>
                  <span className="font-semibold text-slate-700 dark:text-slate-200">{item.season}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Engine:</span>
                  <span className="font-semibold text-slate-700 dark:text-slate-200">{item.prediction_source}</span>
                </div>
              </div>

              <button className="w-full py-2.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-bold rounded-xl text-xs transition-colors flex items-center justify-center gap-1">
                View Full Snapshot <ChevronRight className="w-3 h-3" />
              </button>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
};

export default RecommendationHistory;
